version: '3.9'

services:
    db:
        container_name: postgres-db
        image: postgres:14.5-alpine3.16
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_MULTIPLE_DATABASES: dev,test
        volumes:
            - ./docker/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    db-admin:
        container_name: pgadmin4-db
        image: dpage/pgadmin4:6.13
        restart: always
        ports:
            - ${PGADMIN_PORT}:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        depends_on:
            - db
